/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;
import Logica.GloboIzq;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import Logica.monkey;
/**
 *
 * @author DELL
 */
public class MonkeyPlusInterfaz extends javax.swing.JFrame {
    monkey MiMonkey;
    /**
     * Creates new form MonkeyPlusInterfaz
     */
    GloboIzq globoizq ;
    Graphics Graphics;
    
        int pasod=0;
        int pasoi=0;
    public MonkeyPlusInterfaz() {
        initComponents();
        MiMonkey = new monkey(JPanel1);
        this.setLocationRelativeTo(null);
        setResizable(false);
        globoizq = new GloboIzq();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GloboIZQ = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        JPanel1 = new javax.swing.JPanel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(853, 480));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(GloboIZQ);
        GloboIZQ.setBounds(80, 0, 100, 110);

        jButton1.setText("jButton1");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(730, 30, 73, 23);

        JPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MonkeyPlusImagenes/fondo1.jpg"))); // NOI18N
        JPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 860, 480));

        getContentPane().add(JPanel1);
        JPanel1.setBounds(0, 0, 850, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        globoizq.generar_globo(GloboIZQ.getGraphics());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        int x,y;
        x=MiMonkey.cordX();
        y=MiMonkey.cordY();
        String Direc="";
        
        switch(evt.getKeyCode()){
            case KeyEvent.VK_LEFT:
                pasod=0;
                x=x-10;
                if(pasoi==0){ 
                    MiMonkey.Dibujar_monkey(JPanel1.getGraphics(), x, y, 9);
                }else if (pasoi==1){
                     MiMonkey.Dibujar_monkey(JPanel1.getGraphics(), x, y, 10);
                }else if(pasoi==2){
                    MiMonkey.Dibujar_monkey(JPanel1.getGraphics(), x, y, 11);
                }else if(pasoi==3){
                    MiMonkey.Dibujar_monkey(JPanel1.getGraphics(), x, y, 12);
                }else if (pasoi==4){
                     MiMonkey.Dibujar_monkey(JPanel1.getGraphics(), x, y, 13);
                }else if(pasoi==5){
                    MiMonkey.Dibujar_monkey(JPanel1.getGraphics(), x, y, 14);
                }else if(pasoi==6){
                    MiMonkey.Dibujar_monkey(JPanel1.getGraphics(), x, y, 15);
                }else if(pasoi==7){
                    MiMonkey.Dibujar_monkey(JPanel1.getGraphics(), x, y, 16);
                    pasod=0;
                    pasoi=0;
                }
                break;
            case KeyEvent.VK_RIGHT:
                pasoi=0;
                x=x+10;
                   if(pasod==0){
                    MiMonkey.Dibujar_monkey(JPanel1.getGraphics(), x, y, 1);
                }else if (pasod==1){
                     MiMonkey.Dibujar_monkey(JPanel1.getGraphics(), x, y, 2);
                }else if(pasod==2){
                    MiMonkey.Dibujar_monkey(JPanel1.getGraphics(), x, y, 3);
                }else if(pasod==3){
                    MiMonkey.Dibujar_monkey(JPanel1.getGraphics(), x, y, 4);
                }else if(pasod==4){
                    MiMonkey.Dibujar_monkey(JPanel1.getGraphics(), x, y, 5);
                }else if(pasod==5){
                    MiMonkey.Dibujar_monkey(JPanel1.getGraphics(), x, y, 6);
                }else if(pasod==6){
                    MiMonkey.Dibujar_monkey(JPanel1.getGraphics(), x, y, 7);
                }else if(pasod==7){
                    MiMonkey.Dibujar_monkey(JPanel1.getGraphics(), x, y, 8);
                    pasod=0;
                    pasoi=0;
                }
                break;
            case KeyEvent.VK_UP: 
                     MiMonkey.Dibujar_monkey(JPanel1.getGraphics(), x, y, 17);
                break;
        }
        pasoi++;
        pasod++;
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonkeyPlusInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonkeyPlusInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonkeyPlusInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonkeyPlusInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonkeyPlusInterfaz().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel GloboIZQ;
    private javax.swing.JPanel JPanel1;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
